config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users do
    resources :restaurants
    resources :rides
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		@restaurants = Restaurant.all
	end

	def show
		@user = User.find(params[:user_id])
		@restaurant = Restaurant.find(params[:id])
	end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		@rides = Ride.all
	end

	def show
		@user = User.find(params[:user_id])
		@ride = Ride.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Disneat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h2>Restaurants</h2>

<ul>
	<% @restaurants.each do |r| %>
	<li><%= link_to r.name, user_restaurant_path(@user.id, r.id) %></li>
	<% end %>
</ul>

<%= link_to "Rides", user_rides_path(@user.id) %> <%= link_to "Users", users_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<ul>
	<li>Serves Alcohol? <%= @restaurant.serves_alcohol ? "Yes" : "No" %></li>
</ul>

<%= link_to "Rides", user_rides_path(@user.id) %> <%= link_to "Users", users_path %>

app/views/rides/index.html.erb
<h2>Rides</h2>

<ul>
	<% @rides.each do |ride| %>
	<li><%= link_to ride.name, user_ride_path(@user.id, ride.id) %></li>
	<% end %>
</ul>

app/views/rides/show.html.erb
<h2><%= @ride.name %></h2>
<ul>
	<li>Minimum Height: <%= @ride.min_height %></li>
</ul>

<%= link_to "Restaurants", user_restaurants_path(@user.id) %>
<%= link_to "Users", users_path %>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
	<% @users.each do |user| %>
	<li><%= link_to user.name, user_path(user.id) %></li>
	<% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<ul>
	<li>Name: <%= @user.name %></li>
	<li>Age: <%= @user.age %></li>
	<li>Height: <%= @user.height %></li>
</ul>

<%= link_to "Restaurants", user_restaurants_path(@user.id) %>
<%= link_to "Rides", user_rides_path(@user.id) %>